default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  # NOTE - THIS IS SET HIGHER THAN THE USUAL RAILS DEFAULT SOLELY FOR SIDEKIQ
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>
  timeout: 5000
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'test123' %>

development:
  <<: *default
  database: dpl_cms_development

test:
  <<: *default
  database: dpl_cms_test<%= ENV['TEST_ENV_NUMBER'] %>
