# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d43a25f254b70a483f2042adecf44b7e53dcac5d71d7d3fa3893fa4ce151c8cfb7495f6df50b4413dfbe64da22180c4343ab789cc8fb18b81bc7518c19bbbd47

test:
  secret_key_base: 0dcc0a4c57ada0714a87bc991567805ab514fc2bf95360169fff75d774e65040343bf935cfcb3e91ce7277c086dede9065157d2d2022eb0080a83bf4feed29f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
